### ISSUE TITLE
Prevent text selection after double click

### ISSUE THREAD

**Issue by wahidkadwaikar** [teamrebca/viser-theme#5]
If a user double clicks on client name in agenda, it selects the name along with checbox. It's better if we avoid that behaviour wherever appropriate in our application. The following code disables user-select.

```scss
.some-class {
  -webkit-user-select: none; /* webkit (safari, chrome) browsers */
  -moz-user-select: none; /* mozilla browsers */
  -khtml-user-select: none; /* webkit (konqueror) browsers */
  -ms-user-select: none; /* IE10+ */
}
```

Reference: [https://developer.mozilla.org/en-US/docs/Web/CSS/user-select](url)
